//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiscordBotCore.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PokePointsUser
    {
        public int ID { get; set; }
        public string UserID { get; set; }
        public Nullable<int> Points { get; set; }
    }
}
