//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiscordBotCore.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PokeNames
    {
        public int IDPokeNames { get; set; }
        public string NamesGerman { get; set; }
        public string NamesEnglish { get; set; }
        public string Pics { get; set; }
        public string ShadowPics { get; set; }
    }
}
